@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>>{
Interface ReadOnlyPersonBook <<Interface>>
Interface Model <<Interface>>
Interface ObservableList <<Interface>>
Class PersonBook
Interface ReadOnlyPersonBook <<Interface>>
Class BookingBook
Interface ReadOnlyBookingBook <<Interface>>
Class RoomBook
Interface ReadOnlyRoomBook <<Interface>>
Class RoomServiceBook
Interface ReadOnlyRoomServiceBook <<Interface>>
Class Model
Class ModelManager
Class UserPrefs
Class ReadOnlyUserPrefs

Package Person {
Class Person
Class Address
Class Email
Class Name
Class Phone
Class UniquePersonList
}

Package Tag {
Class Tag
}

Package Booking {
Class Booking
Class UniqueBookingList
}

Package Room {
Abstract Room
Class Single
Class Double
Class Suite
Class UniqueRoomList
}

Package RoomService {
Class RoomService
}
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

PersonBook ..|> ReadOnlyPersonBook
RoomServiceBook ..|> ReadOnlyRoomServiceBook
BookingBook ..|> ReadOnlyBookingBook
RoomBook ..|> ReadOnlyRoomBook

ModelManager .up.|> Model
Model .right.> ObservableList
ModelManager o--> "1" PersonBook
ModelManager o------> "1" RoomBook
ModelManager o--> "1" BookingBook
ModelManager o-------> "1" RoomServiceBook
ModelManager o-left-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

PersonBook *--> "1" UniquePersonList
UniquePersonList o--> "*" Person
Person *--> Name
Person *--> Phone
Person *--> Email
Person *--> Address
Person *--> "*" Tag

BookingBook *--> "1" UniqueBookingList
UniqueBookingList o--> "*" Booking

RoomBook *--> "1" UniqueRoomList
UniqueRoomList o--> "*" Room
Single .up.|> Room
Double .up.|> Room
Suite .up.|> Room

RoomServiceBook *--> "*" RoomService

Name -[hidden]right-> Phone
Phone -[hidden]right-> Address
Address -[hidden]right-> Email

ModelManager -->"1" Person : filtered list
ModelManager -->"1" Booking : filtered list
@enduml
